server:
  servlet:
    contextPath: /api
  params: -tcp -tcpAllowOthers -tcpPort 9090

spring:
  datasource:
    url: jdbc:h2:mem:citydb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
