INSERT INTO CITY (name, description)
VALUES ('TEST_NAME_1', 'TEST_DESCRIPTION_1'),
        ('TEST_NAME_2', 'TEST_DESCRIPTION_2'),
        ('TEST_NAME_3', 'TEST_DESCRIPTION_3'),
        ('TEST_NAME_4', 'TEST_DESCRIPTION_4');